#encoding: utf-8
class CreateCities < ActiveRecord::Migration
  def change
    create_table :cities do |t|
      t.string :name
      t.string :alias
      t.string :domain

      t.timestamps
    end

    City.create(name: "Абакан", alias: "Abakan", domain: "abakan")
	City.create(name: "Анапа", alias: "Anapa", domain: "anapa")
	City.create(name: "Архангельск", alias: "Arkhangelsk", domain: "arkhangelsk")
	City.create(name: "Астрахань", alias: "Astrakhan", domain: "astrakhan")
	City.create(name: "Барнаул", alias: "Barnaul", domain: "barnaul")
	City.create(name: "Белгород", alias: "Belgorod", domain: "belgorod")
	City.create(name: "Белогорск", alias: "Belogorsk", domain: "belogorsk")
	City.create(name: "Бийск", alias: "Biysk", domain: "biysk")
	City.create(name: "Биробиджан", alias: "Birobidzhan", domain: "birobidzhan")
	City.create(name: "Благовещенск", alias: "Blagoveshchensk", domain: "blagoveshchensk")
	City.create(name: "Брянск", alias: "Bryansk", domain: "bryansk")
	City.create(name: "Великий Новгород", alias: "Veliky Novgorod", domain: "veliky-novgorod")
	City.create(name: "Владивосток", alias: "Vladivostok", domain: "vladivostok")
	City.create(name: "Владимир", alias: "Vladimir", domain: "vladimir")
	City.create(name: "Волгоград", alias: "Volgograd", domain: "volgograd")
	City.create(name: "Волжск", alias: "Volzhsk", domain: "volzhsk")
	City.create(name: "Волжский", alias: "Voljskii", domain: "voljskii")
	City.create(name: "Вологда", alias: "Vologda", domain: "vologda")
	City.create(name: "Воронеж", alias: "Voronezh", domain: "voronezh")
	City.create(name: "Димитровград", alias: "Dimitrovgrad", domain: "dimitrovgrad")
	City.create(name: "Екатеринбург", alias: "Ekaterinburg", domain: "ekaterinburg")
	City.create(name: "Зеленоград", alias: "Zelenograd", domain: "zelenograd")
	City.create(name: "Иваново", alias: "Ivanovo", domain: "ivanovo")
	City.create(name: "Ижевск", alias: "Izhevsk", domain: "izhevsk")
	City.create(name: "Иркутск", alias: "Irkutsk", domain: "irkutsk")
	City.create(name: "Йошкар-Ола", alias: "Yoshkar_Ola", domain: "yoshkar-ola")
	City.create(name: "Казань", alias: "Kazan", domain: "kazan")
	City.create(name: "Калининград", alias: "Kaliningrad", domain: "kaliningrad")
	City.create(name: "Калуга", alias: "Kaluga", domain: "kaluga")
	City.create(name: "Кемерово", alias: "Kemerovo", domain: "kemerovo")
	City.create(name: "Киров", alias: "Kirov", domain: "kirov")
	City.create(name: "Кострома", alias: "Kostroma", domain: "kostroma")
	City.create(name: "Краснодар", alias: "Krasnodar", domain: "krasnodar")
	City.create(name: "Красноярск", alias: "Krasnoyarsk", domain: "krasnoyarsk")
	City.create(name: "Курган", alias: "Kurgan", domain: "kurgan")
	City.create(name: "Курск", alias: "Kursk", domain: "kursk")
	City.create(name: "Липецк", alias: "Lipetsk", domain: "lipetsk")
	City.create(name: "Магнитогорск", alias: "Magnitogorsk", domain: "magnitogorsk")
	City.create(name: "Миасс", alias: "Miass", domain: "miass")
	City.create(name: "Минск", alias: "Minsk", domain: "minsk")
	City.create(name: "Москва", alias: "Moscow", domain: "moscow")
	City.create(name: "Мурманск", alias: "Murmansk", domain: "murmansk")
	City.create(name: "Наб.Челны", alias: "Nab.Chelny", domain: "nab-chelny")
	City.create(name: "Ниж.Новгород", alias: "Nizh.Novgorod", domain: "nizh-novgorod")
	City.create(name: "Ниж.Тагил", alias: "Nizh.Tagil", domain: "nizh-tagil")
	City.create(name: "Нижневартовск", alias: "Nizhnevartovsk", domain: "nizhnevartovsk")
	City.create(name: "Нов. Уренгой", alias: "New.Urengoy", domain: "new-urengoy")
	City.create(name: "Новокузнецк", alias: "Novokuznetsk", domain: "novokuznetsk")
	City.create(name: "Новороссийск", alias: "Novorossiysk", domain: "novorossiysk")
	City.create(name: "Новосибирск", alias: "Novosibirsk", domain: "novosibirsk")
	City.create(name: "Ноябрьск", alias: "Noyabrsk", domain: "noyabrsk")
	City.create(name: "Октябрьский", alias: "Oktyabrskiy", domain: "oktyabrskiy")
	City.create(name: "Омск", alias: "Omsk", domain: "omsk")
	City.create(name: "Орел", alias: "Orel", domain: "orel")
	City.create(name: "Оренбург", alias: "Orenburg", domain: "orenburg")
	City.create(name: "Орск", alias: "Orsk", domain: "orsk")
	City.create(name: "Пенза", alias: "Penza", domain: "penza")
	City.create(name: "Пермь", alias: "Perm", domain: "perm")
	City.create(name: "Петрозаводск", alias: "Petrozavodsk", domain: "petrozavodsk")
	City.create(name: "Псков", alias: "Pskov", domain: "pskov")
	City.create(name: "Пятигорск", alias: "Pyatigorsk", domain: "pyatigorsk")
	City.create(name: "Ростов-на-Дону", alias: "Rostov_na_Donu", domain: "rostov-na-donu")
	City.create(name: "Рыбинск", alias: "Rybinsk", domain: "rybinsk")
	City.create(name: "Рязань", alias: "Ryazan", domain: "ryazan")
	City.create(name: "Самара", alias: "Samara", domain: "samara")
	City.create(name: "Санкт-Петербург", alias: "St.Petersburg", domain: "st-petersburg")
	City.create(name: "Саранск", alias: "Saransk", domain: "saransk")
	City.create(name: "Саратов", alias: "Saratov", domain: "saratov")
	City.create(name: "Смоленск", alias: "Smolensk", domain: "smolensk")
	City.create(name: "Сочи", alias: "Sochi", domain: "sochi")
	City.create(name: "Ставрополь", alias: "Stavropol", domain: "stavropol")
	City.create(name: "Старый Оскол", alias: "Stary Oskol", domain: "stary-oskol")
	City.create(name: "Стерлитамак", alias: "Sterlitamak", domain: "sterlitamak")
	City.create(name: "Сургут", alias: "Surgut", domain: "surgut")
	City.create(name: "Сызрань", alias: "Syzran", domain: "syzran")
	City.create(name: "Сыктывкар", alias: "Syktyvkar", domain: "syktyvkar")
	City.create(name: "Таганрог", alias: "Taganrog", domain: "taganrog")
	City.create(name: "Тамбов", alias: "Tambov", domain: "tambov")
	City.create(name: "Тверь", alias: "Tver", domain: "tver")
	City.create(name: "Тольятти", alias: "Togliatti", domain: "togliatti")
	City.create(name: "Томск", alias: "Tomsk", domain: "tomsk")
	City.create(name: "Тула", alias: "Tula", domain: "tula")
	City.create(name: "Тюмень", alias: "Tyumen", domain: "tyumen")
	City.create(name: "Улан-Удэ", alias: "Ulan_Ude", domain: "ulan-ude")
	City.create(name: "Ульяновск", alias: "Ulyanovsk", domain: "ulyanovsk")
	City.create(name: "Уссурийск", alias: "Ussuriysk", domain: "ussuriysk")
	City.create(name: "Уфа", alias: "Ufa", domain: "ufa")
	City.create(name: "Хабаровск", alias: "Khabarovsk", domain: "khabarovsk")
	City.create(name: "Ханты-Мансийск", alias: "Khanty_Mansiysk", domain: "khanty-mansiysk")
	City.create(name: "Чебоксары", alias: "Cheboksary", domain: "cheboksary")
	City.create(name: "Челябинск", alias: "Chelyabinsk", domain: "chelyabinsk")
	City.create(name: "Череповец", alias: "Cherepovets", domain: "cherepovets")
	City.create(name: "Чита", alias: "Chita", domain: "chita")
	City.create(name: "Шахты", alias: "Shahty", domain: "shahty")
	City.create(name: "Энгельс", alias: "Engels", domain: "engels")
	City.create(name: "Ярославль", alias: "Yaroslavl", domain: "yaroslavl")
  end
end
